language: erlang
otp_release:
    - 20.2
    - 18.0

services:
    - elasticsearch
    - postgresql

before_script:
    - psql -c 'CREATE USER zotonic;' -U postgres
    - psql -c 'CREATE DATABASE zotonic WITH OWNER = zotonic;' -U postgres
    - psql -c 'GRANT ALL ON DATABASE zotonic TO zotonic;' -U postgres
    - until curl --silent -XGET --fail http://localhost:9200; do printf '.'; sleep 1; done

script:
    - git clone https://github.com/zotonic/zotonic.git /opt/zotonic --branch 0.x
    - mkdir -p /opt/zotonic/user/modules ~/.zotonic
    - cp travis/zotonic.config ~/.zotonic/
    - ln -s $TRAVIS_BUILD_DIR /opt/zotonic/user/modules/
    - cd /opt/zotonic
    - make all
    - bin/zotonic runtests mod_elasticsearch
